Favorites
BAZandpoort/2dekans-veilingen-B pull request #70
Opened 2023-10-11 14:26 UTC by Imad4747

Ik heb ervoor gezorgd dat je producten via het hartje op je favorieten komen op te staan

2023-10-11 14:28 UTC, Imad4747 commented
pak de product bestand van de laatste commit en de rest van favo af

2023-10-11 14:32 UTC, Imad4747 commented
-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Gegenereerd op: 11 okt 2023 om 16:18
-- Serverversie: 10.4.28-MariaDB
-- PHP-versie: 8.2.4

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `2dekans-veilingen`
--

-- --------------------------------------------------------

--
-- Tabelstructuur voor tabel `favorieten`
--

CREATE TABLE `favorieten` (
  `id_num` int(11) NOT NULL,
  `userid` int(30) NOT NULL,
  `id` int(30) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Indexen voor geëxporteerde tabellen
--

--
-- Indexen voor tabel `favorieten`
--
ALTER TABLE `favorieten`
  ADD PRIMARY KEY (`id_num`);

--
-- AUTO_INCREMENT voor geëxporteerde tabellen
--

--
-- AUTO_INCREMENT voor een tabel `favorieten`
--
ALTER TABLE `favorieten`
  MODIFY `id_num` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=6;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;

2023-10-11 14:36 UTC, Imad4747 commented
[-- phpMyAdmin SQL Dump.txt](https://github.com/BAZandpoort/2dekans-veilingen-B/files/12871155/--.phpMyAdmin.SQL.Dump.txt)

2023-10-11 17:06 UTC, CedricVerlinden requested changes
There is an issue when adding a product to your favorites: when for example adding the product with id 1, it will add the product with id 2 to my list.

2023-10-11 17:06 UTC, CedricVerlinden commented on src/lib/catalog/products.php
> +
Not needed, already required

2023-10-16 16:38 UTC, CedricVerlinden commented
@Imad4747

2023-10-20 19:12 UTC, CedricVerlinden commented
Is this still a valid pull request or has this been replaced by #84 ?

2023-10-21 11:08 UTC, CedricVerlinden commented
Closed due to #84

2023-10-21 11:08 UTC, closed without merging